# Generated by Django 4.1.7 on 2023-02-23 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="Name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="booking",
            name="No_of_guests",
            field=models.IntegerField(max_length=11),
        ),
    ]
